---
sections:
- template: section_cards
  header: Two or more column layout with header
  text: A header with text and two column layout. Columns have a little gap, so
    background color comes through. 2,3 or 4 columns. Cards freely choosable
  cards: true
  fields:
    - header
    - text
  options:
    - background
    - columns
    - color
- template: section_full_up
  header: Centered Header with text
  text: Full width header with centered headline and optional text
  fields:
    - header
    - text
  options:
    - background
    - color
    - button_link
    - button_text
- template: section_half_image
  header: Split section with image left or right
  text: Image on one side, header and text on the other.
    Order depends on order option. Optional button.
  fields:
    - header
    - text
  options:
    - order
    - background
    - color
    - subheader
    - text
    - align
    - button_link
    - button_text
- template: section_full_image
  header: Full image header with adjustable text
  text: Large picture background with Header and text towards
    adjustable alignment (left, center, right).
    Text may be slightly shaded for readability,
    text color can be changed too
  fields:
    - header
    - text
  options:
    - fixed
    - color
    - align
    - shade_color
- template: section_spacer
  header: Spacer
  text: Just for extra padding
  fields:
cards:
- template: card_full_image
  header: Full background
  text: With text in bottom right corner, offset with solid color
  fields:
    - header
    - text
- template: card_normal_square
  header: Standard card with square image
  text: Image, header, text, normal stuff
  fields:
    - header
    - text
  options:
    - background
    - color
    - align
    - subheader
- template: card_normal_round
  header: Standard card with square image
  text: Image, header, text, normal stuff
  fields:
    - header
    - text
options:
  - name: fixed
    desciption:
      Paralax effect where background stays fixed
      during scrolling
    values: on off
    default: off
  - name: columns
    desciption:
      Number of columns in a layout that supports cards
    values: 2 3 4
    default: 3
  - name: background
    desciption:
      Background colors. Light colors stay with black text.
      Solid colors invert to white text.
    values: white none light_blue light_grey light_orange solid_blue solid_red solid_indigo
    default: none
  - name: color
    desciption:
      Text colors. Don't use with solid background colors.
      Same colors as background available. Default none, meas as parent.
    values: none white light_blue light_grey solid_black solid_blue solid_red solid_indigo
    default: none
  - name: shade_color
    desciption:
      Color of transparent shaded area.
      The number means transparency.
    values: none black_25 white_25 light_red_25 light_blue_25 solid_blue_25 solid_red_25
    default: none
  - name: align
    desciption:
      Align text of children. Normal Word meaning
    values: left center right
    default: left
  - name: order
    desciption:
      For two column layout determine order of sub-cards
      Values of left and right usually refer to where the image is
      For cards it can also mean up and down
    values: left right
    default: left
  - name: button_text
    desciption:
      Text for an optional button. Must also set button_link
    values:
    default:
  - name: subheader
    desciption:
      Smaller header between Header and text
    values:
    default:
  - name: text
    desciption:
      Second text. Just a second paragraph
    values:
    default:
  - name: button_link
    desciption:
      Link for an option button. Must also set button_text.
      Link must be a page name, ie only internal links allowed.
    values:
    default:
