---
sections:
- template: section_2_col
  header: Two column  layout with header
  text: A header with text and two column layout. Columns have a little gap, so
    background color comes through.
  cards: true
  fields:
    - header
    - text
- template: section_full_up
  header: Centered Header with text
  text: Full width header with centered headline and optional text
  fields:
    - header
    - text
- template: section_half_image
  header: Split section with image left or right
  text: Image on one side, header and text on the other.
    Order depends on order option. Optional button.
  fields:
    - header
    - text
  options:
    - button_link
    - button_text
    - order
    - background
- template: section_full_left
  header: Full image header, text left
  text: Large picture background with Header and text towards the left.
    Text is slightly shaded for readability
  fields:
    - header
    - text
  options:
    - fixed
- template: section_spacer
  header: Spacer
  text: Just for extra padding
  fields:
cards:
- template: card_full_image
  header: Full background
  text: With text in bottom right corner, offset with solid color
  fields:
    - header
    - text
options:
  - name: fixed
    desciption:
      Paralax effect where background stays fixed
      during scrolling
    values: on off
    default: off
  - name: background
    desciption:
      Slight background color
    values: white blue
    default: white
  - name: order
    desciption:
      For two column layout determine order of sub-cards
      Values of left and right usually refer to where the image is
    values: left right
    default: left
  - name: button_text
    desciption:
      Text for an optional button. Must also set button_link
    values:
    default:
  - name: button_link
    desciption:
      Link for an option button. Must also set button_text.
      Link must be a page name, ie only internal links allowed.
    values:
    default:
