---
- template: card_full_image
  header: Full background
  text: Text in box on top of the imag. Adjustable background
            and text color to mix/match with images.
  fields:
    - header
    - text
  options:
    - background
    - color
    - text_align
- template: card_gap_square
  header: Narrow card with up down section
  text: Smaller image, large margins, possible subheader
    Order turns it upside down, image bottom
  fields:
    - header
    - text
  options:
    - background
    - color
    - order
    - text_align
    - subheader
- template: card_normal_square
  header: Standard card with square image
  text: Image, header, text, normal stuff. No margin between image and text.
        Possible subheader. Text alignment option. Also option to turn upside
        down with order.
  fields:
    - header
    - text
  options:
    - background
    - color
    - text_align
    - subheader
    - order
- template: card_wide_square
  header: Sideway card with square image
  text: Much like standard square card, just turned sideways.
  fields:
    - header
    - text
  options:
    - background
    - color
    - text_align
    - subheader
    - order
- template: card_normal_round
  header: Standard card with rounded look
  text: Otherwise quite similar to standard. But there is gap under the image.
  fields:
    - header
    - text
  options:
    - background
    - color
    - text_align
- template: form_field
  header: A single field in a form
  text: The header is the Name of the field, the description
        serves as a placeholder.
  fields:
    - header
    - text
  options:
    - compulsory
    - form_type
